# Generated by Django 3.1 on 2020-08-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counsellor',
            name='profile',
        ),
        migrations.AddField(
            model_name='counsellor',
            name='profile_photo',
            field=models.ImageField(default='default_avatar.jpg', upload_to='profile_pics'),
        ),
    ]
