# Generated by Django 3.1 on 2020-09-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='time',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
    ]
