# Generated by Django 3.1 on 2020-09-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200901_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportgroup',
            name='image',
            field=models.ImageField(default='image.jpg', upload_to='group_profiles'),
        ),
    ]
