# Generated by Django 3.1 on 2020-08-31 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20200827_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counsellor',
            name='profile_photo',
            field=models.ImageField(default='default_avatar.jpg', upload_to='profile_pics'),
        ),
    ]
