# Generated by Django 3.1 on 2020-09-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_supportgroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='issue',
            field=models.TextField(blank=True, null=True),
        ),
    ]
