# Generated by Django 3.1 on 2020-09-03 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_discussion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discussion',
        ),
    ]
