# Generated by Django 3.1 on 2020-09-07 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20200907_1736'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
