# Generated by Django 3.1 on 2020-09-07 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
