# Generated by Django 3.1 on 2020-09-07 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_delete_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.client')),
            ],
        ),
    ]
